### ISSUE TITLE
Datos faltantes y duplicados en result_resumen_por_mesa.csv

### ISSUE THREAD

**Issue by grossir** [rburhum/elecciones-peru-2021-ONPE#3]
Revisando los datos en .csv del primer [commit](https://github.com/rburhum/elecciones-peru-2021-ONPE/commit/d70e1feb46f8c78f6b72a2800b575e89e1c9bb53#diff-3a6eb0790f39ac87c94f3856b2dd2c5d110e6811602261a9a923d3bb23adc8b7)  porque contienen votos de primera vuelta, hay algunos problemas.

- Hay 77983 filas, vs 82821 de la siguiente version. 
- Hay filas duplicadas. Por ejemplo, ver id=225 y id=5174, ambas con codigo de mesa 000169

### Solucion
Para quien este analizando los datos, la solucion es quedarse con la fila que tenga el ultimo last_updated

**Comment by rburhum** [comment]
Gracias! Actualicé los datos después de este request. Estoy actualizando los datos de nuevo... Saludos!
